### ISSUE TITLE
Métodos privados (podem) esconder classes

### ISSUE THREAD

**Issue by fabriciofx** [caarlos0/oop-clock#3]
IMHO, métodos privados (podem) esconder classes. Assim, por exemplo, o método ```diff()``` da classe ```Angle```, deveria ser refatorado para virar uma nova classe que seria passada ao construtor ```Angle```. Poderíamos ter algo assim:

```
interface Calculation<R> {
  R exec();
}

final class DiffCalculation implements Calculation<Integer> {
  Integer exec() {
    // faz igual ao método diff da classe Angle
  }
}
```

E depois passar ao construtor da classe ```Angle``` esse ```Calculation``` e também ter um construtor
secundário que receberia um objeto ```DiffCalculation``` por default.

**Comment by caarlos0** [comment]
Poderia, mas esse projeto foi só uma "brincadeira" e está abandonado.

Não leve a mal, mas não vou mexer nele..
Se quiser abrir um PR, pode ficar a vontade :)

E obrigado pelo feedback!
